export enum Constants {
    GET_COMPANIES_OK = 'GET_COMPANIES_OK',
    GET_COMPANIES_ERROR = 'GET_COMPANIES_ERROR',
    SET_IS_LOADING = 'SET_IS_LOADING',
    SET_IS_SAVING = 'SET_IS_SAVING',
    UPDATE_BUDGET_OK = 'UPDATE_BUDGET_OK',
    UPDATE_BUDGET_ERROR = 'UPDATE_BUDGET_ERROR',
    SET_UPDATE_SUCCESS = 'SET_UPDATE_SUCCESS',
    SET_SELECTED_COMPANY_ID = 'SET_SELECTED_COMPANY_ID',
}
